dependencies:
 matplotlib==1.5.1
 Pandas==0.18.1
 pytables==3.2.2
 pip:
    flask==0.12
    Flask-Bootstrap==3.3.5.7
    Flask-Plugins==1.6.1
    Flask-Testing==0.6.1
    Flask-Uploads==0.2.1
    Flask-WTF==0.14.2
    Jinja2==2.8
    mpld3==0.2
    pytest==2.8.5
    pytest-flask==0.10.0
    service-identity==16.0.0
    WTForms==2.1
    WTForms-Components==0.10.0
