name: Evert
channels:
- defaults
dependencies:
- coveralls
- coverage=4.3.4
- cycler=0.10.0
- flask=0.12
- flask-migrate=2.0.3
- flask-script=2.0.5
- flask-socketio=2.8.4
- flask-sqlalchemy=2.2
- flask-testing=0.6.1
- flask-uploads=0.2.1
- flask-wtf=0.14.2
- gevent=1.2.1
- greenlet=0.4.12
- jinja2=2.9.5
- matplotlib=2.0.0
- mock==2.0.0
- pandas=0.19.2
- pip=9.0.1
- pytest=2.8.5
- pytest-cov=2.4.0
- pytest-mock==1.5.0
- scipy=0.19.0
- setuptools=27.2.0
- sqlalchemy=1.1.6
- pip:
  - cryptography==1.7.2
  - eventlet==0.17.4
  - flask-bootstrap==3.3.5.7
  - flask-plugins==1.6.1
  - pytest-flask==0.10.0
  - service-identity==16.0.0
  - wtforms==2.1
  - wtforms-components==0.10.0

